import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "../context/SidebarContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          {children}
          <Toaster
            position="bottom-right"
            reverseOrder={false}
            toastOptions={{
              className: 'text-[17px] pt-30',
              style: {
                padding: '12px 16px',
                borderRadius: '8px',
              },
            }}
          />
        </SidebarProvider>
      </body>
    </html>
  );
}
